### ISSUE TITLE
Nested example failure

### ISSUE THREAD

**Issue by adamchainz** [asottile/blacken-docs#126]
I was writing about using blacken-docs and it crashed like:

```
$ python -m blacken_docs example.rst
Traceback (most recent call last):
  File "/.../3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.../3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/.../site-packages/blacken_docs.py", line 248, in <module>
    exit(main())
  File "/.../site-packages/blacken_docs.py", line 243, in main
    retv |= format_file(filename, black_mode, skip_errors=args.skip_errors)
  File "/.../site-packages/blacken_docs.py", line 199, in format_file
    new_contents, errors = format_str(contents, black_mode)
  File "/.../site-packages/blacken_docs.py", line 186, in format_str
    src = RST_RE.sub(_rst_match, src)
  File "/.../site-packages/blacken_docs.py", line 106, in _rst_match
    min_indent = min(INDENT_RE.findall(match['code']))
ValueError: min() arg is an empty sequence
```

With this `example.rst`:

```
blacken-docs does changes like:

.. code-block:: diff

     .. code-block:: python

    -    name  = 'World'
    -    format_html('Hello <strong>{}</strong>',
    -        name
    -    )
    +    name = "World"
    +    format_html("Hello <strong>{}</strong>", name)
```

It seems blacken-docs picks up `.. code-block:: python`, but then `INDENT_RE` doesn't then due to diff indentation.

(I worked around this by changing the example to not include `.. code-block:: python`.)

**Comment by asottile** [comment]
the crash seems correct, the python block contains non python code

**Comment by adamchainz** [comment]
It's not a real block though because it's in a different code block - perhaps blacken-docs could be taught to ignore code blocks inside code blocks?

**Comment by asottile** [comment]
I doubt it, there isn't a real parser involved
