### ISSUE TITLE
Breaks on hard tab indents in rST

### ISSUE THREAD

**Issue by auscompgeek** [asottile/blacken-docs#138]
reStructuredText allows for using tabs for indenting code-blocks.

```pytb
Traceback (most recent call last):
  File "~/.local/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.10/site-packages/blacken_docs.py", line 246, in main
    retv |= format_file(filename, black_mode, skip_errors=args.skip_errors)
  File "~/.local/lib/python3.10/site-packages/blacken_docs.py", line 202, in format_file
    new_contents, errors = format_str(contents, black_mode)
  File "~/.local/lib/python3.10/site-packages/blacken_docs.py", line 189, in format_str
    src = RST_RE.sub(_rst_match, src)
  File "~/.local/lib/python3.10/site-packages/blacken_docs.py", line 109, in _rst_match
    min_indent = min(INDENT_RE.findall(match['code']))
ValueError: min() arg is an empty sequence

**Comment by asottile** [comment]
dupe #108
