### ISSUE TITLE
Error with black==22.1.0

### ISSUE THREAD

**Issue by ppfeufer** [asottile/blacken-docs#141]
My pre-commit config:
```yaml
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==22.1.0 ]
```

Error:
```
blacken-docs.............................................................Failed
- hook id: blacken-docs
- exit code: 1

Traceback (most recent call last):
  File "/tmp/ppfeufer/.cache/pre-commit/repoh7brsv91/py_env-python3/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/tmp/ppfeufer/.cache/pre-commit/repoh7brsv91/py_env-python3/lib/python3.9/site-packages/blacken_docs.py", line 238, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```

Works perfectly fine with ``black==21.12b0`

pip show black:
```
Name: black
Version: 22.1.0
Summary: The uncompromising code formatter.
Home-page: https://github.com/psf/black
Author: Łukasz Langa
Author-email: lukasz@langa.pl
License: MIT
Location: /mnt/sda1/Development/Python/AllianceAuth/venv-3.9/lib/python3.9/site-packages
Requires: click, mypy-extensions, pathspec, platformdirs, tomli, typing-extensions
Required-by: 
```

**Comment by asottile** [comment]
I'm inclined to believe this is a regression in `black` so let's track it there: https://github.com/psf/black/issues/2829
