### ISSUE TITLE
Incompatible with black v22.1.0

### ISSUE THREAD

**Issue by peterjc** [asottile/blacken-docs#143]
I'm getting this after upgrading to black v22.1.0, using blacken-docs 1.12.0:

```pycon
Traceback (most recent call last):
  File "/Users/xxx/.cache/pre-commit/repo2345cyqn/py_env-python3/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/.cache/pre-commit/repo2345cyqn/py_env-python3/lib/python3.8/site-packages/blacken_docs.py", line 238, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
Traceback (most recent call last):
  File "/Users/xxx/.cache/pre-commit/repo2345cyqn/py_env-python3/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/.cache/pre-commit/repo2345cyqn/py_env-python3/lib/python3.8/site-packages/blacken_docs.py", line 238, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```

**Comment by peterjc** [comment]
Possible one line, line 238:

```python
target_versions=set(args.target_versions),
```

**Comment by asottile** [comment]
dupe #141
