### ISSUE TITLE
--target-version results in KeyError: 'DOCS/INDEX.RST'

### ISSUE THREAD

**Issue by jdufresne** [asottile/blacken-docs#23]
Tested 0.5.0 and master. Black 19.3b0.

When I run with the `--target-version` argument, I receive the following exception:

```
$ blacken-docs --target-version py33 docs/index.rst
Traceback (most recent call last):
  File ".../venv/bin/blacken-docs", line 11, in <module>
    load_entry_point('blacken-docs==0.5.0', 'console_scripts', 'blacken-docs')()
  File ".../venv/lib64/python3.7/site-packages/blacken_docs.py", line 114, in main
    args = parser.parse_args(argv)
  File "/usr/lib64/python3.7/argparse.py", line 1749, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.7/argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.7/argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.7/argparse.py", line 1839, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.7/argparse.py", line 2387, in _get_values
    value = [self._get_value(action, v) for v in arg_strings]
  File "/usr/lib64/python3.7/argparse.py", line 2387, in <listcomp>
    value = [self._get_value(action, v) for v in arg_strings]
  File "/usr/lib64/python3.7/argparse.py", line 2402, in _get_value
    result = type_func(arg_string)
  File ".../venv/lib64/python3.7/site-packages/blacken_docs.py", line 103, in <lambda>
    type=lambda v: black.TargetVersion[v.upper()],
  File "/usr/lib64/python3.7/enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: 'DOCS/INDEX.RST'
```

When I run the same command without the `--target-version` argument, the command works as expected.

**Comment by asottile** [comment]
CC @mxr  -- I believe this is due to `nargs='+'`?
